name: Build Arduino Sketch

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: 'esp32:esp32:esp32s3'
          sketch-paths: |
            - ./
          platforms: |
            - name: esp32:esp32
              source-url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
          libraries: |
            - name: Adafruit NeoPixel